spring:
  application:
    name: math-client
  profiles:
    active: default

server:
  port: 8081

calculator-service:
  url: http://localhost:8080/api/calculator


opentracing:
  jaeger:
    enabled: true
    service-name: ${spring.application.name}
    http-sender:
      url: http://localhost:4318/api/traces
    log-spans: true

#feature-flag.ccc-jaeger.tracing.enabled: true
feature-flag:
  ccc-jaeger:
    tracing:
      enabled: true


logging:
  level:
    org.example.metrics.common: DEBUG
