spring:
  application:
    name: math-client
  profiles:
    active: default

server:
  port: 8081

calculator-service:
  url: http://localhost:8080/api/calculator


opentracing:
  jaeger:
    enable: true
    service-name: math-client
    udp-sender:
      host: localhost
      port: 6831
    log-spans: true

#feature-flag.ccc-jaeger.tracing.enabled: true
feature-flag:
  ccc-jaeger:
    tracing:
      enabled: true


logging:
  level:
    org.example.metrics.common: DEBUG
